title: Монополия Крым
author:
  name: Сергей Мезинов
  email: monopoly.crimea@gmail.com
  phone: +7 (978) 268-52-28
social:
  vk: https://vk.com/monopoly.crimea
  ig: https://instagram.com
metadata:
    description: Настольная игра "Монополия Крым"
